### ISSUE TITLE
Support for `class = ...` in `view!` macro.

### ISSUE THREAD

**Issue by bluenote10** [bram209/leptosfmt#18]
It looks like `leptosfmt` does yet like the `class = ...` syntax introduced in https://github.com/leptos-rs/leptos/pull/351

Small test case:

```rust
use leptos::*;

#[component]
pub fn Test(cx: Scope) -> impl IntoView {
    view! {
        cx,
        class = STYLE,
        <p>"Test paragraph"</p>
    }
}

const STYLE: &str = "some-class";
```

Currently panics with

```
thread 'main' panicked at 'invalid rsx tokens at line: 5:4', /home/fabian/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptosfmt-formatter-0.1.4/src/formatter/mac.rs:14:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/900c3540378c8422b8087ffa3db60fa6c8abfcad/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/900c3540378c8422b8087ffa3db60fa6c8abfcad/library/core/src/panicking.rs:64:14
   2: leptosfmt_formatter::formatter::mac::<impl leptosfmt_formatter::formatter::Formatter>::view_macro
   3: leptosfmt_formatter::source_file::format_source
   4: leptosfmt_formatter::source_file::format_file_source
   5: leptosfmt_formatter::format_file
   6: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &F>::call_mut
   7: <rayon::iter::for_each::ForEachConsumer<F> as rayon::iter::plumbing::Folder<T>>::consume_iter
   8: <rayon::vec::IntoIter<T> as rayon::iter::IndexedParallelIterator>::with_producer
   9: leptosfmt::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
❌ src/fmt_test.rs
		invalid rsx tokens at line: 5:4
Formatted 1 files in 6 ms
```

Removing the `class = STYLE` line makes the example work, indicating that it should be the culprit.

**Comment by bram209** [comment]
Hey, thanks for reporting this. I was not aware of the scoped styling feature of the `view!` macro.
Will fix this soon : )
